In [3]:
import numpy as np

a = [1,1,0]
b = [1,0,1]
 
# Calculating dot product using dot()
print(np.dot(a, b))



1


In [5]:
# l2 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 1, 0])
print(a)
l2 = norm(a)
print(l2)


[1 1 0]
1.4142135623730951


In [8]:
# l2 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 0, 1])
print(a)
l2 = norm(a)
print(l2)

[1 0 1]
1.4142135623730951


In [10]:
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 1, 0])
print(a)
l1 = norm(a, 1)
print(l1)

[1 1 0]
2.0


In [12]:
# l1 norm of a vector
from numpy import array
from numpy.linalg import norm
a = array([1, 0, 1])
print(a)
l1 = norm(a, 1)
print(l1)

[1 0 1]
2.0


In [27]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np
import risk_kit as rk
from pricing_models import StockPricing, FuturesPricing, OptionsPricing

In [30]:
## Building  15 period binomial model with parameters to be calibrated to a Black-Scholes geometric Brownian
## motion model with: T= .25 years , S0 = 100, r = 2%, st dev = 30% and dividend yield of c = 1%


In [33]:
# Setting Paramters
periods = 15
T = 0.25
S0 = 100.00
r = 0.02
sigma = 0.3
c = 0.01

In [36]:
binomial_params = rk.blackscholes_to_binomial(r, sigma, periods, T, c)
u = binomial_params['upward_drift']
d  = binomial_params['downward_drift']
div = binomial_params['dividend_per_period']
rfr = binomial_params['risk_free_rate']
pricing_model =StockPricing(n=periods, S0=S0, u=u, d=d, c=div)


In [38]:
# Q 1 Compute the price of an American call option with strike K=110 and maturity T=.25 years

In [40]:
K = 110
is_call = True
is_american = True
q = ((1+rfr)-d - div)/ (u-d)
call_option = OptionsPricing(n= periods,
                            model=pricing_model,
                            r = rfr,
                            q=q,
                            K=K,
                            is_call = is_call,
                            is_american = is_american)
round(call_option.price, 2)

2.6

In [42]:
#Q 2 Compute the price of an American put option with strike K=110 and maturity T=.25

In [45]:
K = 110
is_call = False
is_american = True

q = ((1+ rfr) -d -div)/(u-d)
put_option = OptionsPricing(n=periods,
                           model=pricing_model,
                           r = rfr,
                           q=q,
                           K=K,
                           is_call=is_call,
                           is_american = is_american)
round(put_option.price,2)


12.36

In [47]:
2 ** 2

4

In [2]:
import math

In [53]:
math.exp(2)

7.38905609893065

In [57]:
1/4 + 1/4 * math.exp(-0.0225) + 1/4 * math.exp(-0.045)

0.733437179756609

In [60]:
(206 + .733437179756609) * math.exp(0.0675)

221.1696867655856

In [62]:
23* math.exp(-0.0125)

22.714289411359275

In [65]:
11.5*math.exp(-0.0125)

11.357144705679637

In [67]:
46* math.exp(-0.05)

43.75655352703284

In [71]:
11.5 * math.exp(-0.05)

10.93913838175821

In [75]:
23 * math.exp(-0.05)

21.87827676351642

In [77]:
math.exp(-0.05)

0.951229424500714

In [80]:
24 * math.exp(-0.05)

22.829506188017135

In [83]:
4.5 * math.exp(-0.03)

4.367004900968286

In [86]:
11.5 * math.exp(-0.0125)

11.357144705679637

In [89]:
11.5*math.exp(-0.0041)

11.452946525536706

In [93]:
math.exp(-0.0041) * 11.5

11.452946525536706

In [96]:
50*0.25

12.5

In [99]:
12.5 - 11.4529

1.0471000000000004

In [101]:
math.exp(-0.0041)

0.995908393524931

In [104]:
11.5 * math.exp(-0.05)

10.93913838175821

In [107]:
12.5 - 10.9391

1.5609000000000002

In [109]:
math.exp(0.01)

1.010050167084168

In [111]:
8* 0.428

3.424

In [114]:
3.424/1.01

3.39009900990099

In [116]:
15* 0.488

7.32

In [5]:
math.exp(0.01)

1.010050167084168

In [9]:
math.exp(0.3)

1.3498588075760032

In [11]:
1.34985 -0.9

0.44984999999999997

In [15]:
0.44984/0.2

2.2492

In [18]:
math.exp(0.025)

1.0253151205244289

In [20]:
1.02531 - 0.9

0.12530999999999992

In [22]:
0.12530/0.2

0.6265

In [25]:
1 - 0.6265

0.37350000000000005

In [27]:
(0.6265*61.72) + (0.3735* 35.96)

52.098639999999996

In [29]:
52.0986* math.exp(-0.025)

50.81228098279929

In [30]:
math.exp(-0.025)

0.9753099120283326